#!/bin/bash
set -eu

[ -x /usr/sbin/semanage ] || exit 0

semanage fcontext -a -t swift_var_cache_t ""$STATEFUL_PATH"/var/cache/swift(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/var/cache/swift

# allows rsync to write to "$STATEFUL_PATH"/var/log/rsyncd.log
semanage fcontext -a -t var_log_t ""$STATEFUL_PATH"/var/log"
restorecon -Rv "$STATEFUL_PATH"/var/log

# relabel "$STATEFUL_PATH"/srv/node as swift_data_t for selinux before the service
# is started. Otherwise selinux will deny writes to this directory.
semanage fcontext -a -t swift_data_t ""$STATEFUL_PATH"/srv/node"
restorecon -Rv "$STATEFUL_PATH"/srv/node
