#!/bin/bash
set -eux

[ -d "$STATEFUL_PATH"/var/lib/rabbitmq ] || install -d -D -m 0770 -o rabbitmq -g rabbitmq /mnt/state/var/lib/rabbitmq
install -m 600 -o rabbitmq -g rabbitmq /dev/null "$STATEFUL_PATH"/var/lib/rabbitmq/.erlang.cookie
[ -d "$STATEFUL_PATH"/var/log/rabbitmq ] || install -d -D -m 0770 -o rabbitmq -g rabbitmq /mnt/state/var/log/rabbitmq
