#!/bin/bash
set -eux

# Allow openssl to read keys

[ -x /usr/sbin/semanage ] || exit 0

semanage fcontext -a -t cert_t ""$STATEFUL_PATH"/etc/keystone/ssl(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/etc/keystone/ssl
