#!/bin/bash

set -eux

install-packages openstack-glance

# When glance-manage is run as root during os-refresh-config it will create the
# initial glance registry log file root owned, and then the glance service will
# fail to start. Create the initial glance owned log file here instead.
touch /var/log/glance/registry.log
touch /var/log/glance/api.log
chown -R glance.glance /var/log/glance

DISTRO=`lsb_release -si` || true
if [[ "RedHatEnterpriseServer CentOS Fedora" =~ "$DISTRO" ]]; then
    # The package installs for these variants drop their config under
    # /usr/share/glance.  We need the paste ini files symlinked under
    # /etc/glance, and the conf files symlinked under /usr/share/glance.
    ln -s /usr/share/glance/glance-api-dist-paste.ini /etc/glance/glance-api-paste.ini
    ln -s /usr/share/glance/glance-registry-dist-paste.ini /etc/glance/glance-registry-paste.ini
    ln -f -s /etc/glance/glance-api.conf /usr/share/glance/glance-api-dist.conf
    ln -f -s /etc/glance/glance-cache.conf /usr/share/glance/glance-cache-dist.conf
    ln -f -s /etc/glance/glance-registry.conf /usr/share/glance/glance-registry-dist.conf
    ln -f -s /etc/glance/glance-scrubber.conf /usr/share/glance/glance-scrubber-dist.conf
fi
