#!/bin/bash
set -eux

os-svc-enable -n ceilometer-api

[ -d "$STATEFUL_PATH"/var/lib/ceilometer ] || install -d -D -m 0770 -o ceilometer -g ceilometer /mnt/state/var/lib/ceilometer
[ -d "$STATEFUL_PATH"/var/lib/ceilometer/keystone-signing ] || install -d -D -m 0770 -o ceilometer -g ceilometer /mnt/state/var/lib/ceilometer/keystone-signing

service ceilometer-api restart
