#!/bin/bash
set -eu

OK="$STATEFUL_PATH"/var/lib/boot-stack/init-openstack.ok

if ! os-is-bootstrap-host || [ -e $OK ] ; then
    exit 0
fi

PATH=/usr/local/bin:$PATH

reset-db

mkdir -p $(dirname $OK)
touch $OK
