#!/bin/bash
set -eu

# Update selinux so that mysql has access to "$STATEFUL_PATH".
# It runs in pre-configure.d because permissions needs to be correct before
# reset-db is called in configure.d/51-init-openstack.

[ -x /usr/sbin/semanage ] || exit 0

semanage fcontext -a -t mysqld_db_t ""$STATEFUL_PATH"/var/lib/mysql(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/var/lib/mysql
semanage fcontext -a -t mysqld_log_t ""$STATEFUL_PATH"/var/log/mysql(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/var/log/mysql
[ -d "$STATEFUL_PATH"/etc/mysql ] || install -m 0755 -o mysql -g mysql -d /mnt/state/etc/mysql
semanage fcontext -a -t mysqld_etc_t ""$STATEFUL_PATH"/etc/mysql(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/etc/mysql

# /var/lib/mysql needs to be set to mysqld_db_t
restorecon -R /var/lib/mysql
