#!/bin/bash
set -ue

[ -d "$STATEFUL_PATH"/var/lib/glance ] || install -d -D -m 0770 -o glance -g glance "$STATEFUL_PATH"/var/lib/glance
[ -d "$STATEFUL_PATH"/var/lib/glance/images ] || install -d -D -m 0770 -o glance -g glance "$STATEFUL_PATH"/var/lib/glance/images
[ -d "$STATEFUL_PATH"/var/log/glance ] || install -d -D -m 0755 -o glance -g glance "$STATEFUL_PATH"/var/log/glance
