#!/bin/bash
set -eu

[ -x /usr/sbin/semanage ] || exit 0

semanage fcontext -a -t glance_var_lib_t ""$STATEFUL_PATH"/var/lib/glance(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/var/lib/glance

semanage fcontext -a -t glance_log_t ""$STATEFUL_PATH"/var/log/glance(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/var/log/glance
