#!/bin/bash
set -eux

mkdir -p "$STATEFUL_PATH"/var/lib/nova/instances/_base
chown nova:kvm "$STATEFUL_PATH"/var/lib/nova/instances
chown nova:kvm "$STATEFUL_PATH"/var/lib/nova/instances/_base
chmod 750 "$STATEFUL_PATH"/var/lib/nova/instances
chmod 750 "$STATEFUL_PATH"/var/lib/nova/instances/_base
