#!/bin/bash
set -eux

mkdir -p "$STATEFUL_PATH"/var/log/trove
chown -R trove:trove "$STATEFUL_PATH"/var/log/trove

trove-manage --config-file /etc/trove/trove.conf db_sync

os-svc-enable -n trove-api

os-svc-restart -n trove-api
