#!/bin/bash
set -ue

[ -d "$STATEFUL_PATH"/var/lib/nova ] && exit 0
install -D -d -o nova -g nova -m 0775 "$STATEFUL_PATH"/var/lib/nova
[ -d "$STATEFUL_PATH"/var/log/nova ] && exit 0
install -D -d -o nova -g nova -m 0775 "$STATEFUL_PATH"/var/log/nova
