#!/bin/bash
set -eu

[ -x /usr/sbin/semanage ] || exit 0

semanage fcontext -a -t nova_var_lib_t ""$STATEFUL_PATH"/var/lib/nova(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/var/lib/nova

semanage fcontext -a -t nova_log_t ""$STATEFUL_PATH"/var/log/nova(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/var/log/nova
