#!/bin/bash
set -eu

[ -x /usr/sbin/semanage ] || exit 0

semanage fcontext -a -t rabbitmq_var_lib_t ""$STATEFUL_PATH"/var/lib/rabbitmq(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/var/lib/rabbitmq

semanage fcontext -a -t rabbitmq_var_log_t ""$STATEFUL_PATH"/var/log/rabbitmq(/.*)?"
restorecon -Rv "$STATEFUL_PATH"/var/log/rabbitmq
