#!/bin/bash

set -eux

OK_FILE=/opt/stack/.undercloud-setup

if [ -f $OK_FILE ]; then
    exit
fi

source /root/stackrc

cp /root/stackrc /etc/sysconfig/undercloudrc

# Add scripts directory from tripleo-incubator to the path.
if [ ! -e /etc/profile.d/tripleo-incubator-scripts.sh ]; then
    echo export PATH=\$PATH:/opt/stack/tripleo-incubator/scripts/ >> \
        /etc/profile.d/tripleo-incubator-scripts.sh
fi

# Make sure we have the latest $PATH set.
source /etc/profile.d/tripleo-incubator-scripts.sh

if [ ! -f /root/.ssh/authorized_keys ]; then
    sudo mkdir -p /root/.ssh
    sudo chmod 7000 /root/.ssh/
    sudo touch /root/.ssh/authorized_keys
    sudo chmod 600 /root/.ssh/authorized_keys
fi

if [ ! -f /root/.ssh/id_rsa ]; then
    ssh-keygen -b 1024 -N '' -f /root/.ssh/id_rsa
fi

cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys

# Ensure keystone is up before continuing on.
# Waits for up to 2 minutes.
wait_for 12 10 systemctl status keystone

# Because keystone just still isn't up yet...
sleep 20

export UNDERCLOUD_IP=192.0.2.1

init-keystone -p unset unset \
    $UNDERCLOUD_IP admin@example.com root@$UNDERCLOUD_IP

setup-endpoints \
    $UNDERCLOUD_IP \
    --glance-password unset \
    --heat-password unset \
    --neutron-password unset \
    --nova-password unset

keystone role-create --name heat_stack_user

setup-neutron 192.0.2.5 192.0.2.24 192.0.2.0/24 192.0.2.1 $UNDERCLOUD_IP ctlplane

make -C /opt/stack/tripleo-heat-templates overcloud.yaml

touch $OK_FILE
