#!/bin/bash
set -eu

[ -d "$STATEFUL_PATH"/var/lib/neutron ] || install -d -D -m 0770 -o neutron -g neutron "$STATEFUL_PATH"/var/lib/neutron
[ -d /var/run/neutron ] || install -D -m 0775 -o neutron -g neutron -d /var/run/neutron
[ -d "$STATEFUL_PATH"/var/log/neutron ] || install -D -m 0775 -o neutron -g neutron -d "$STATEFUL_PATH"/var/log/neutron
